/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaIndexRouteImport } from './routes/qa.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as QaNewRouteImport } from './routes/qa.new'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsHistoryRouteImport } from './routes/agents.history'
import { Route as AgentsApprovalsRouteImport } from './routes/agents.approvals'
import { Route as AgentsTaskIdRouteImport } from './routes/agents.$taskId'
import { Route as ApiPublicWebhooksAgentEventRouteImport } from './routes/api.public.webhooks.agent-event'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/qa/',
  path: '/qa/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QaNewRoute = QaNewRouteImport.update({
  id: '/qa/new',
  path: '/qa/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsHistoryRoute = AgentsHistoryRouteImport.update({
  id: '/agents/history',
  path: '/agents/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsApprovalsRoute = AgentsApprovalsRouteImport.update({
  id: '/agents/approvals',
  path: '/agents/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsTaskIdRoute = AgentsTaskIdRouteImport.update({
  id: '/agents/$taskId',
  path: '/agents/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksAgentEventRoute =
  ApiPublicWebhooksAgentEventRouteImport.update({
    id: '/api/public/webhooks/agent-event',
    path: '/api/public/webhooks/agent-event',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$taskId': typeof AgentsTaskIdRoute
  '/agents/approvals': typeof AgentsApprovalsRoute
  '/agents/history': typeof AgentsHistoryRoute
  '/agents/new': typeof AgentsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/qa/new': typeof QaNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/qa/': typeof QaIndexRoute
  '/api/public/webhooks/agent-event': typeof ApiPublicWebhooksAgentEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$taskId': typeof AgentsTaskIdRoute
  '/agents/approvals': typeof AgentsApprovalsRoute
  '/agents/history': typeof AgentsHistoryRoute
  '/agents/new': typeof AgentsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/qa/new': typeof QaNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/agents': typeof AgentsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/qa': typeof QaIndexRoute
  '/api/public/webhooks/agent-event': typeof ApiPublicWebhooksAgentEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$taskId': typeof AgentsTaskIdRoute
  '/agents/approvals': typeof AgentsApprovalsRoute
  '/agents/history': typeof AgentsHistoryRoute
  '/agents/new': typeof AgentsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/qa/new': typeof QaNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/qa/': typeof QaIndexRoute
  '/api/public/webhooks/agent-event': typeof ApiPublicWebhooksAgentEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/agents/$taskId'
    | '/agents/approvals'
    | '/agents/history'
    | '/agents/new'
    | '/projects/$id'
    | '/projects/new'
    | '/qa/new'
    | '/runs/$id'
    | '/agents/'
    | '/projects/'
    | '/qa/'
    | '/api/public/webhooks/agent-event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/agents/$taskId'
    | '/agents/approvals'
    | '/agents/history'
    | '/agents/new'
    | '/projects/$id'
    | '/projects/new'
    | '/qa/new'
    | '/runs/$id'
    | '/agents'
    | '/projects'
    | '/qa'
    | '/api/public/webhooks/agent-event'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/agents/$taskId'
    | '/agents/approvals'
    | '/agents/history'
    | '/agents/new'
    | '/projects/$id'
    | '/projects/new'
    | '/qa/new'
    | '/runs/$id'
    | '/agents/'
    | '/projects/'
    | '/qa/'
    | '/api/public/webhooks/agent-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AgentsTaskIdRoute: typeof AgentsTaskIdRoute
  AgentsApprovalsRoute: typeof AgentsApprovalsRoute
  AgentsHistoryRoute: typeof AgentsHistoryRoute
  AgentsNewRoute: typeof AgentsNewRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  QaNewRoute: typeof QaNewRoute
  RunsIdRoute: typeof RunsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  QaIndexRoute: typeof QaIndexRoute
  ApiPublicWebhooksAgentEventRoute: typeof ApiPublicWebhooksAgentEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/qa'
      fullPath: '/qa/'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/new': {
      id: '/qa/new'
      path: '/qa/new'
      fullPath: '/qa/new'
      preLoaderRoute: typeof QaNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/history': {
      id: '/agents/history'
      path: '/agents/history'
      fullPath: '/agents/history'
      preLoaderRoute: typeof AgentsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/approvals': {
      id: '/agents/approvals'
      path: '/agents/approvals'
      fullPath: '/agents/approvals'
      preLoaderRoute: typeof AgentsApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$taskId': {
      id: '/agents/$taskId'
      path: '/agents/$taskId'
      fullPath: '/agents/$taskId'
      preLoaderRoute: typeof AgentsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/agent-event': {
      id: '/api/public/webhooks/agent-event'
      path: '/api/public/webhooks/agent-event'
      fullPath: '/api/public/webhooks/agent-event'
      preLoaderRoute: typeof ApiPublicWebhooksAgentEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AgentsTaskIdRoute: AgentsTaskIdRoute,
  AgentsApprovalsRoute: AgentsApprovalsRoute,
  AgentsHistoryRoute: AgentsHistoryRoute,
  AgentsNewRoute: AgentsNewRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  QaNewRoute: QaNewRoute,
  RunsIdRoute: RunsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  QaIndexRoute: QaIndexRoute,
  ApiPublicWebhooksAgentEventRoute: ApiPublicWebhooksAgentEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
