/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PathwaysRouteImport } from './routes/pathways'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaIndexRouteImport } from './routes/qa.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as RosterPersonasRouteImport } from './routes/roster.personas'
import { Route as RosterAgentsRouteImport } from './routes/roster.agents'
import { Route as QaNewRouteImport } from './routes/qa.new'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AppsPublishedRouteImport } from './routes/apps.published'
import { Route as AppsNewRouteImport } from './routes/apps.new'
import { Route as AppsIdRouteImport } from './routes/apps.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsHistoryRouteImport } from './routes/agents.history'
import { Route as AgentsApprovalsRouteImport } from './routes/agents.approvals'
import { Route as AgentsTaskIdRouteImport } from './routes/agents.$taskId'
import { Route as QaRunsRunIdRouteImport } from './routes/qa.runs.$runId'
import { Route as AppsIdSubmitRouteImport } from './routes/apps.$id.submit'
import { Route as ApiPublicWebhooksAgentEventRouteImport } from './routes/api.public.webhooks.agent-event'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api.public.payments.webhook'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysRoute = PathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIndexRoute = QaIndexRouteImport.update({
  id: '/qa/',
  path: '/qa/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterPersonasRoute = RosterPersonasRouteImport.update({
  id: '/roster/personas',
  path: '/roster/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterAgentsRoute = RosterAgentsRouteImport.update({
  id: '/roster/agents',
  path: '/roster/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const QaNewRoute = QaNewRouteImport.update({
  id: '/qa/new',
  path: '/qa/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPublishedRoute = AppsPublishedRouteImport.update({
  id: '/apps/published',
  path: '/apps/published',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsNewRoute = AppsNewRouteImport.update({
  id: '/apps/new',
  path: '/apps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIdRoute = AppsIdRouteImport.update({
  id: '/apps/$id',
  path: '/apps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsHistoryRoute = AgentsHistoryRouteImport.update({
  id: '/agents/history',
  path: '/agents/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsApprovalsRoute = AgentsApprovalsRouteImport.update({
  id: '/agents/approvals',
  path: '/agents/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsTaskIdRoute = AgentsTaskIdRouteImport.update({
  id: '/agents/$taskId',
  path: '/agents/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRunsRunIdRoute = QaRunsRunIdRouteImport.update({
  id: '/qa/runs/$runId',
  path: '/qa/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIdSubmitRoute = AppsIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppsIdRoute,
} as any)
const ApiPublicWebhooksAgentEventRoute =
  ApiPublicWebhooksAgentEventRouteImport.update({
    id: '/api/public/webhooks/agent-event',
    path: '/api/public/webhooks/agent-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/pathways': typeof PathwaysRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/agents/$taskId': typeof AgentsTaskIdRoute
  '/agents/approvals': typeof AgentsApprovalsRoute
  '/agents/history': typeof AgentsHistoryRoute
  '/agents/new': typeof AgentsNewRoute
  '/apps/$id': typeof AppsIdRouteWithChildren
  '/apps/new': typeof AppsNewRoute
  '/apps/published': typeof AppsPublishedRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/qa/new': typeof QaNewRoute
  '/roster/agents': typeof RosterAgentsRoute
  '/roster/personas': typeof RosterPersonasRoute
  '/runs/$id': typeof RunsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/qa/': typeof QaIndexRoute
  '/apps/$id/submit': typeof AppsIdSubmitRoute
  '/qa/runs/$runId': typeof QaRunsRunIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/agent-event': typeof ApiPublicWebhooksAgentEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/pathways': typeof PathwaysRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/agents/$taskId': typeof AgentsTaskIdRoute
  '/agents/approvals': typeof AgentsApprovalsRoute
  '/agents/history': typeof AgentsHistoryRoute
  '/agents/new': typeof AgentsNewRoute
  '/apps/$id': typeof AppsIdRouteWithChildren
  '/apps/new': typeof AppsNewRoute
  '/apps/published': typeof AppsPublishedRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/qa/new': typeof QaNewRoute
  '/roster/agents': typeof RosterAgentsRoute
  '/roster/personas': typeof RosterPersonasRoute
  '/runs/$id': typeof RunsIdRoute
  '/agents': typeof AgentsIndexRoute
  '/apps': typeof AppsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/qa': typeof QaIndexRoute
  '/apps/$id/submit': typeof AppsIdSubmitRoute
  '/qa/runs/$runId': typeof QaRunsRunIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/agent-event': typeof ApiPublicWebhooksAgentEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/pathways': typeof PathwaysRoute
  '/settings': typeof SettingsRoute
  '/upgrade': typeof UpgradeRoute
  '/agents/$taskId': typeof AgentsTaskIdRoute
  '/agents/approvals': typeof AgentsApprovalsRoute
  '/agents/history': typeof AgentsHistoryRoute
  '/agents/new': typeof AgentsNewRoute
  '/apps/$id': typeof AppsIdRouteWithChildren
  '/apps/new': typeof AppsNewRoute
  '/apps/published': typeof AppsPublishedRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/qa/new': typeof QaNewRoute
  '/roster/agents': typeof RosterAgentsRoute
  '/roster/personas': typeof RosterPersonasRoute
  '/runs/$id': typeof RunsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/qa/': typeof QaIndexRoute
  '/apps/$id/submit': typeof AppsIdSubmitRoute
  '/qa/runs/$runId': typeof QaRunsRunIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/agent-event': typeof ApiPublicWebhooksAgentEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/history'
    | '/pathways'
    | '/settings'
    | '/upgrade'
    | '/agents/$taskId'
    | '/agents/approvals'
    | '/agents/history'
    | '/agents/new'
    | '/apps/$id'
    | '/apps/new'
    | '/apps/published'
    | '/projects/$id'
    | '/projects/new'
    | '/qa/new'
    | '/roster/agents'
    | '/roster/personas'
    | '/runs/$id'
    | '/agents/'
    | '/apps/'
    | '/projects/'
    | '/qa/'
    | '/apps/$id/submit'
    | '/qa/runs/$runId'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/agent-event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/history'
    | '/pathways'
    | '/settings'
    | '/upgrade'
    | '/agents/$taskId'
    | '/agents/approvals'
    | '/agents/history'
    | '/agents/new'
    | '/apps/$id'
    | '/apps/new'
    | '/apps/published'
    | '/projects/$id'
    | '/projects/new'
    | '/qa/new'
    | '/roster/agents'
    | '/roster/personas'
    | '/runs/$id'
    | '/agents'
    | '/apps'
    | '/projects'
    | '/qa'
    | '/apps/$id/submit'
    | '/qa/runs/$runId'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/agent-event'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/history'
    | '/pathways'
    | '/settings'
    | '/upgrade'
    | '/agents/$taskId'
    | '/agents/approvals'
    | '/agents/history'
    | '/agents/new'
    | '/apps/$id'
    | '/apps/new'
    | '/apps/published'
    | '/projects/$id'
    | '/projects/new'
    | '/qa/new'
    | '/roster/agents'
    | '/roster/personas'
    | '/runs/$id'
    | '/agents/'
    | '/apps/'
    | '/projects/'
    | '/qa/'
    | '/apps/$id/submit'
    | '/qa/runs/$runId'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/agent-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  PathwaysRoute: typeof PathwaysRoute
  SettingsRoute: typeof SettingsRoute
  UpgradeRoute: typeof UpgradeRoute
  AgentsTaskIdRoute: typeof AgentsTaskIdRoute
  AgentsApprovalsRoute: typeof AgentsApprovalsRoute
  AgentsHistoryRoute: typeof AgentsHistoryRoute
  AgentsNewRoute: typeof AgentsNewRoute
  AppsIdRoute: typeof AppsIdRouteWithChildren
  AppsNewRoute: typeof AppsNewRoute
  AppsPublishedRoute: typeof AppsPublishedRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  QaNewRoute: typeof QaNewRoute
  RosterAgentsRoute: typeof RosterAgentsRoute
  RosterPersonasRoute: typeof RosterPersonasRoute
  RunsIdRoute: typeof RunsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AppsIndexRoute: typeof AppsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  QaIndexRoute: typeof QaIndexRoute
  QaRunsRunIdRoute: typeof QaRunsRunIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWebhooksAgentEventRoute: typeof ApiPublicWebhooksAgentEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways': {
      id: '/pathways'
      path: '/pathways'
      fullPath: '/pathways'
      preLoaderRoute: typeof PathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/': {
      id: '/qa/'
      path: '/qa'
      fullPath: '/qa/'
      preLoaderRoute: typeof QaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/personas': {
      id: '/roster/personas'
      path: '/roster/personas'
      fullPath: '/roster/personas'
      preLoaderRoute: typeof RosterPersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/agents': {
      id: '/roster/agents'
      path: '/roster/agents'
      fullPath: '/roster/agents'
      preLoaderRoute: typeof RosterAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/new': {
      id: '/qa/new'
      path: '/qa/new'
      fullPath: '/qa/new'
      preLoaderRoute: typeof QaNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/published': {
      id: '/apps/published'
      path: '/apps/published'
      fullPath: '/apps/published'
      preLoaderRoute: typeof AppsPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/new': {
      id: '/apps/new'
      path: '/apps/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AppsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$id': {
      id: '/apps/$id'
      path: '/apps/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AppsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/history': {
      id: '/agents/history'
      path: '/agents/history'
      fullPath: '/agents/history'
      preLoaderRoute: typeof AgentsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/approvals': {
      id: '/agents/approvals'
      path: '/agents/approvals'
      fullPath: '/agents/approvals'
      preLoaderRoute: typeof AgentsApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$taskId': {
      id: '/agents/$taskId'
      path: '/agents/$taskId'
      fullPath: '/agents/$taskId'
      preLoaderRoute: typeof AgentsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/runs/$runId': {
      id: '/qa/runs/$runId'
      path: '/qa/runs/$runId'
      fullPath: '/qa/runs/$runId'
      preLoaderRoute: typeof QaRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$id/submit': {
      id: '/apps/$id/submit'
      path: '/submit'
      fullPath: '/apps/$id/submit'
      preLoaderRoute: typeof AppsIdSubmitRouteImport
      parentRoute: typeof AppsIdRoute
    }
    '/api/public/webhooks/agent-event': {
      id: '/api/public/webhooks/agent-event'
      path: '/api/public/webhooks/agent-event'
      fullPath: '/api/public/webhooks/agent-event'
      preLoaderRoute: typeof ApiPublicWebhooksAgentEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppsIdRouteChildren {
  AppsIdSubmitRoute: typeof AppsIdSubmitRoute
}

const AppsIdRouteChildren: AppsIdRouteChildren = {
  AppsIdSubmitRoute: AppsIdSubmitRoute,
}

const AppsIdRouteWithChildren =
  AppsIdRoute._addFileChildren(AppsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  PathwaysRoute: PathwaysRoute,
  SettingsRoute: SettingsRoute,
  UpgradeRoute: UpgradeRoute,
  AgentsTaskIdRoute: AgentsTaskIdRoute,
  AgentsApprovalsRoute: AgentsApprovalsRoute,
  AgentsHistoryRoute: AgentsHistoryRoute,
  AgentsNewRoute: AgentsNewRoute,
  AppsIdRoute: AppsIdRouteWithChildren,
  AppsNewRoute: AppsNewRoute,
  AppsPublishedRoute: AppsPublishedRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  QaNewRoute: QaNewRoute,
  RosterAgentsRoute: RosterAgentsRoute,
  RosterPersonasRoute: RosterPersonasRoute,
  RunsIdRoute: RunsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AppsIndexRoute: AppsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  QaIndexRoute: QaIndexRoute,
  QaRunsRunIdRoute: QaRunsRunIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWebhooksAgentEventRoute: ApiPublicWebhooksAgentEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
